# Generated by Django 5.1.2 on 2024-10-24 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('reforming', '0002_dailydataraforming'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyDataRaforming',
            new_name='DailyDataReforming',
        ),
    ]
