# Generated by Django 5.1.2 on 2024-10-25 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reforming', '0003_rename_dailydataraforming_dailydatareforming'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailydatareforming',
            old_name='unit100',
            new_name='u100_data',
        ),
        migrations.RenameField(
            model_name='dailydatareforming',
            old_name='unit200',
            new_name='u200_data',
        ),
        migrations.RenameField(
            model_name='dailydatareforming',
            old_name='unit250',
            new_name='u250_data',
        ),
        migrations.RenameField(
            model_name='dailydatareforming',
            old_name='unit300',
            new_name='u300_data',
        ),
        migrations.RenameField(
            model_name='dailydatareforming',
            old_name='unit350',
            new_name='u350_data',
        ),
    ]
