# Generated by Django 5.1.2 on 2024-10-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='u500',
            name='bt_rate',
            field=models.FloatField(blank=True, help_text='79.072', null=True, verbose_name='BT[T/Hr]'),
        ),
        migrations.AlterField(
            model_name='u500',
            name='bt_water_content',
            field=models.FloatField(blank=True, help_text='<100', null=True, verbose_name='BT Water Content (ppm)'),
        ),
        migrations.AlterField(
            model_name='u500',
            name='capacity_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Capacity %'),
        ),
        migrations.AlterField(
            model_name='u500',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='u500',
            name='morpholin_in_bt',
            field=models.FloatField(blank=True, help_text='<50', null=True, verbose_name='Morpholin In BT (ppm)'),
        ),
        migrations.AlterField(
            model_name='u500',
            name='morpholin_in_raffinate',
            field=models.FloatField(blank=True, help_text='<50', null=True, verbose_name='Morpholin In Raffinate (ppm)'),
        ),
        migrations.AlterField(
            model_name='u500',
            name='na_in_bt',
            field=models.FloatField(blank=True, help_text='<2%', null=True, verbose_name='N.A. in BT'),
        ),
        migrations.AlterField(
            model_name='u500',
            name='nfm_on_bt',
            field=models.FloatField(blank=True, help_text='1-3 ppm', null=True, verbose_name='NFM on BT (ppm)'),
        ),
        migrations.AlterField(
            model_name='u500',
            name='nfm_on_raffinate',
            field=models.FloatField(blank=True, help_text='1~3ppm', null=True, verbose_name='NFM on RAFFINATE (ppm)'),
        ),
        migrations.AlterField(
            model_name='u500',
            name='raffinate',
            field=models.FloatField(blank=True, help_text='47.808', null=True, verbose_name='Raffinate[T/Hr]'),
        ),
        migrations.AlterField(
            model_name='u500',
            name='t_5001_feed_rate',
            field=models.FloatField(blank=True, help_text='126.88', null=True, verbose_name='T-5001[T/Hr]'),
        ),
        migrations.AlterField(
            model_name='u500',
            name='t_5002_feed_rate',
            field=models.FloatField(blank=True, help_text='537.596', null=True, verbose_name='T-5002[T/Hr]'),
        ),
        migrations.AlterField(
            model_name='u500',
            name='total_lean_solvent',
            field=models.FloatField(blank=True, help_text='432', null=True, verbose_name='Total Lean Solvent [M3/Hr]'),
        ),
        migrations.AlterField(
            model_name='u600',
            name='benzene_purity',
            field=models.FloatField(blank=True, help_text='0.999', null=True, verbose_name='Benzene Purity'),
        ),
        migrations.AlterField(
            model_name='u600',
            name='br_i_in_clay_outlet',
            field=models.FloatField(blank=True, help_text='10 max', null=True, verbose_name='Br.I in clay outlet'),
        ),
        migrations.AlterField(
            model_name='u600',
            name='bz_production_rate',
            field=models.FloatField(blank=True, help_text='54.435', null=True, verbose_name='Bz production rate[T/Hr]'),
        ),
        migrations.AlterField(
            model_name='u600',
            name='capacity_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Capacity %'),
        ),
        migrations.AlterField(
            model_name='u600',
            name='compressor_hp_purge',
            field=models.FloatField(blank=True, null=True, verbose_name='(Compressor HP Purge)(Nm3/hr)'),
        ),
        migrations.AlterField(
            model_name='u600',
            name='conversion_rate',
            field=models.FloatField(blank=True, help_text='47-49', null=True, verbose_name='Conversion Rate %'),
        ),
        migrations.AlterField(
            model_name='u600',
            name='d_6004_A_dp',
            field=models.FloatField(blank=True, help_text='...', null=True, verbose_name='D-6004A    ΔP'),
        ),
        migrations.AlterField(
            model_name='u600',
            name='d_6004_B_dp',
            field=models.FloatField(blank=True, help_text='...', null=True, verbose_name='D-6004B   ΔP'),
        ),
        migrations.AlterField(
            model_name='u600',
            name='d_6004_ـAB_inlet_temp',
            field=models.FloatField(blank=True, help_text='150-200', null=True, verbose_name='D-6004A/B : Inlet Temp (°C)'),
        ),
        migrations.AlterField(
            model_name='u600',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='u600',
            name='h2_hc_ratio',
            field=models.FloatField(blank=True, help_text='3 min', null=True, verbose_name='H2/HC Ratio'),
        ),
        migrations.AlterField(
            model_name='u600',
            name='mx_production_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='MX Production Rate (T/Hr)'),
        ),
        migrations.AlterField(
            model_name='u600',
            name='r_6001_dp',
            field=models.FloatField(blank=True, help_text='0.7', null=True, verbose_name='R-6001 ΔP'),
        ),
        migrations.AlterField(
            model_name='u600',
            name='r_6001_dt',
            field=models.FloatField(blank=True, help_text='25', null=True, verbose_name='R-6001 ΔT'),
        ),
        migrations.AlterField(
            model_name='u600',
            name='r_6001_feed_non_aro',
            field=models.FloatField(blank=True, help_text='<2%', null=True, verbose_name='R-6001 Feed Non Aro %'),
        ),
        migrations.AlterField(
            model_name='u600',
            name='r_6001_press',
            field=models.FloatField(blank=True, help_text='28', null=True, verbose_name='R-6001 Press'),
        ),
        migrations.AlterField(
            model_name='u600',
            name='r_6001_temp',
            field=models.FloatField(blank=True, help_text='360-480', null=True, verbose_name='R-6001 Temp (°C)'),
        ),
        migrations.AlterField(
            model_name='u600',
            name='t_6001_feed_rate',
            field=models.FloatField(blank=True, help_text='94.276', null=True, verbose_name='T-6001[T/Hr]'),
        ),
        migrations.AlterField(
            model_name='u600',
            name='t_6002_feed_rate',
            field=models.FloatField(blank=True, help_text='174.24', null=True, verbose_name='T-6002[T/Hr]'),
        ),
        migrations.AlterField(
            model_name='u600',
            name='t_6002_non_aro_side_cut',
            field=models.FloatField(blank=True, help_text='0.05(0.07ims)', null=True, verbose_name='T-6002 Non Aro% Side Cut'),
        ),
        migrations.AlterField(
            model_name='u600',
            name='t_6003_bott_non_aro',
            field=models.FloatField(blank=True, help_text='0.0017', null=True, verbose_name='T-6003 Bott. Non Aro'),
        ),
        migrations.AlterField(
            model_name='u600',
            name='t_6003_feed_rate',
            field=models.FloatField(blank=True, help_text='119.804', null=True, verbose_name='T-6003[T/Hr]'),
        ),
        migrations.AlterField(
            model_name='u600',
            name='t_6003_toluene_bott',
            field=models.FloatField(blank=True, help_text='0.1', null=True, verbose_name='T-6003 Toluene Bott. %'),
        ),
        migrations.AlterField(
            model_name='u600',
            name='tk_6001_bt_from_sec_500',
            field=models.FloatField(blank=True, help_text='80.954', null=True, verbose_name='TK-6001[T/Hr]+BT from SEC-500'),
        ),
        migrations.AlterField(
            model_name='u600',
            name='unit_600_recycle',
            field=models.FloatField(blank=True, help_text='Sm3/hr', null=True, verbose_name='Unit 600 Recycle'),
        ),
        migrations.AlterField(
            model_name='u600',
            name='water_content_recycle_gas',
            field=models.FloatField(blank=True, help_text='10 ppm', null=True, verbose_name='Water Content (Recycle gas)'),
        ),
        migrations.AlterField(
            model_name='u600',
            name='xylene_yield',
            field=models.FloatField(blank=True, help_text='21-23%', null=True, verbose_name='Xylene Yield'),
        ),
        migrations.AlterField(
            model_name='u650',
            name='br_i_in_clay_outlet',
            field=models.FloatField(blank=True, help_text='10 max', null=True, verbose_name='Br.I in clay outlet'),
        ),
        migrations.AlterField(
            model_name='u650',
            name='capacity_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Capacity %'),
        ),
        migrations.AlterField(
            model_name='u650',
            name='conversion_rate',
            field=models.FloatField(blank=True, help_text='80-87', null=True, verbose_name='Conversion Rate %'),
        ),
        migrations.AlterField(
            model_name='u650',
            name='d_6505_A_dp',
            field=models.FloatField(blank=True, help_text='...', null=True, verbose_name='D-6505A    ΔP'),
        ),
        migrations.AlterField(
            model_name='u650',
            name='d_6505_B_dp',
            field=models.FloatField(blank=True, help_text='...', null=True, verbose_name='D-6505B ΔP'),
        ),
        migrations.AlterField(
            model_name='u650',
            name='d_6505_inlet_temp',
            field=models.FloatField(blank=True, help_text='150-200', null=True, verbose_name='D-6505A/B : Inlet Temp'),
        ),
        migrations.AlterField(
            model_name='u650',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='u650',
            name='h2_hc_ratio',
            field=models.FloatField(blank=True, help_text='3 MIN', null=True, verbose_name='H2/HC Ratio'),
        ),
        migrations.AlterField(
            model_name='u650',
            name='heavy_aro',
            field=models.FloatField(blank=True, help_text='2.009', null=True, verbose_name='Heavy Aro [T/Hr]'),
        ),
        migrations.AlterField(
            model_name='u650',
            name='mx_production_rate',
            field=models.FloatField(blank=True, help_text='Sm3/hr', null=True, verbose_name='Unit 650 Recycle'),
        ),
        migrations.AlterField(
            model_name='u650',
            name='r_6501_dp',
            field=models.FloatField(blank=True, help_text='0.7', null=True, verbose_name='R-6501 ΔP'),
        ),
        migrations.AlterField(
            model_name='u650',
            name='r_6501_dt',
            field=models.FloatField(blank=True, help_text='50', null=True, verbose_name='R-6501 ΔT'),
        ),
        migrations.AlterField(
            model_name='u650',
            name='r_6501_press',
            field=models.FloatField(blank=True, help_text='28', null=True, verbose_name='R-6501 Press'),
        ),
        migrations.AlterField(
            model_name='u650',
            name='r_6501_temp',
            field=models.FloatField(blank=True, help_text='360-472', null=True, verbose_name='R-6501 Temp (°C)'),
        ),
        migrations.AlterField(
            model_name='u650',
            name='t_6501_feed_rate',
            field=models.FloatField(blank=True, help_text='76.691', null=True, verbose_name='T-6501[T/Hr]'),
        ),
        migrations.AlterField(
            model_name='u650',
            name='t_6501_side_cut_c10',
            field=models.FloatField(blank=True, help_text='0.25', null=True, verbose_name='T-6501 Side Cut C10+'),
        ),
        migrations.AlterField(
            model_name='u650',
            name='t_6502_feed_rate',
            field=models.FloatField(blank=True, help_text='114.046', null=True, verbose_name='T-6502[T/Hr]'),
        ),
        migrations.AlterField(
            model_name='u650',
            name='t_6503_feed_rate',
            field=models.FloatField(blank=True, help_text='106.059', null=True, verbose_name='T-6503[T/Hr]'),
        ),
        migrations.AlterField(
            model_name='u650',
            name='t_6503_toluene_bott',
            field=models.FloatField(blank=True, help_text='0.05', null=True, verbose_name='T-6503 Bott. Toluene'),
        ),
        migrations.AlterField(
            model_name='u650',
            name='water_content_recycle_gas',
            field=models.FloatField(blank=True, help_text='10 ppm', null=True, verbose_name='Water Content (Recycle Gas)'),
        ),
        migrations.AlterField(
            model_name='u650',
            name='xylene_yield',
            field=models.FloatField(blank=True, help_text='31-35%', null=True, verbose_name='Xylene Yield'),
        ),
    ]
