# Generated by Django 5.1.2 on 2024-10-24 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('btx', '0002_alter_u500_bt_rate_alter_u500_bt_water_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDataBtx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('u500_data', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_data_u500', to='btx.u500')),
                ('u600_data', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_data_u600', to='btx.u600')),
                ('u650_data', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_data_u650', to='btx.u650')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_daily_btx', to='accounts.profile')),
            ],
        ),
    ]
