# Generated by Django 5.1.2 on 2024-10-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='U400',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('capacity_percent', models.FloatField(verbose_name='Capacity %')),
                ('feed_rate', models.FloatField(help_text='646.858', verbose_name='FEED RATE [T/Hr]')),
                ('t_4001_feed_rate', models.FloatField(help_text='238.26', verbose_name='T-4001[T/Hr]')),
                ('t_4002_total_feed_rate', models.FloatField(help_text='375.2', verbose_name='T-4002[T/Hr] Total')),
                ('t_4003_total_feed_rate', models.FloatField(help_text='144.8', verbose_name='T-4003[T/Hr] Total')),
                ('t_4004_feed_rate', models.FloatField(help_text='46.079', verbose_name='T-4004[T/Hr]')),
                ('edf_feed_rate', models.FloatField(help_text='126.88', verbose_name='EDF[T/Hr]')),
                ('non_aro_t_4002_top', models.FloatField(help_text='0.1', verbose_name='Non Aro at T-4002 top')),
                ('non_aro_t_4003_top', models.FloatField(help_text='0.1', verbose_name='Non Aro at T-4003 top')),
                ('c8a_t_4002_bott', models.FloatField(blank=True, help_text='0.3', null=True, verbose_name='C8A at T-4002 Bott')),
                ('c8a_t_4004_bott', models.FloatField(blank=True, help_text='Nil', null=True, verbose_name='C8A at T-4004 Bott')),
                ('non_aro_t_4001_bott', models.FloatField(help_text='0.3', verbose_name='Non Aro at T-4001 Bott')),
                ('bz_t_4001_bott', models.FloatField(help_text='0', verbose_name='BZ at T-4001 Bott')),
                ('tol_t_4001_bott', models.FloatField(help_text='0.4', verbose_name='TOL at T-4001 Bott')),
                ('d_4005a_b_inlet_temp', models.FloatField(help_text='170-199', verbose_name='D-4005A/B : Inlet Temp')),
                ('d_4005a_dp', models.FloatField(help_text='1.5', verbose_name='D-4005A ΔP')),
                ('d_4005b_dp', models.FloatField(help_text='1.5', verbose_name='D-4005B ΔP')),
                ('bri_clay_outlet_a', models.FloatField(blank=True, help_text='10 max', null=True, verbose_name='BrI in clay outlet(A)')),
                ('bri_clay_outlet_b', models.FloatField(blank=True, help_text='10 max', null=True, verbose_name='BrI in clay outlet(B)')),
                ('c8_aro_top_t_4001', models.FloatField(help_text='0.1', verbose_name='C8 ARO (Top T-4001) (%)')),
                ('c9_aro_top_t_4002', models.FloatField(help_text='0.05', verbose_name='C9 ARO (Top T-4002) (%)')),
                ('c9_aro_top_t_4003', models.FloatField(help_text='0.05', verbose_name='C9 ARO (Top T-4003) (%)')),
                ('ox_production_rate', models.FloatField(help_text='12.626', verbose_name='OX PRODUCTION RATE T/h')),
                ('non_aro_on_ox', models.FloatField(help_text='1% IMS', verbose_name='Non Aro. On OX')),
                ('ox_purity', models.FloatField(help_text='0.985', verbose_name='OX PURITY(%)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='U700',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('capacity_percent', models.FloatField(verbose_name='Capacity %')),
                ('tuning_status', models.CharField(help_text='New Setpoint', max_length=255, verbose_name='Tuning Status')),
                ('feed_t_7001_a_b', models.FloatField(help_text='426.57', verbose_name='FEED T-7001 A/B T/H')),
                ('bri_feed_to_t_7001a_b', models.FloatField(help_text='MAX 10', verbose_name='Br.I in Feed to T-7001A/B')),
                ('t_7001a_temp', models.FloatField(help_text='175', verbose_name='T-7001A/B Temp.[ ºc]')),
                ('t_7001a_dp', models.FloatField(help_text='MAX 4.5', verbose_name='T-7001A ΔP( MAX) Within 24 Hour')),
                ('t_7001b_dp', models.FloatField(help_text='MAX 4.5', verbose_name='T-7001B ΔP(MAX) Within 24 Hour')),
                ('water_injection', models.FloatField(help_text='100', verbose_name='Water injection (Kg/Hr)')),
                ('water_feed_ppm', models.FloatField(help_text='max 40', verbose_name='Water: Feed [ ppm]')),
                ('water_desorbent_ppm', models.FloatField(help_text='MAx 140 ppm', verbose_name='Water: Desorbent [ ppm]')),
                ('water_raff_ppm', models.FloatField(help_text='MAx 100 ppm', verbose_name='Water: Raff [ ppm]')),
                ('px_on_raffinate', models.FloatField(help_text='0.005', verbose_name='Px on Raffinate:')),
                ('px_rate', models.FloatField(help_text='94.205', verbose_name='Px Rate[T/Hr.]')),
                ('tol_rate', models.FloatField(help_text='1.881', verbose_name='TOL Rate[T/Hr.]')),
                ('px_purity', models.FloatField(help_text='99.7', verbose_name='PURITY OF PX')),
                ('pdeb_in_px_prod', models.FloatField(help_text='0', verbose_name='PDEB In:PX Prod.')),
                ('pdeb_in_side_cut', models.FloatField(help_text='0', verbose_name='PDEB In: Side Cut:')),
                ('make_up_recycle_pdeb_purity', models.FloatField(help_text='>98%wt', verbose_name='Make up/ Recycle PDEB Purity')),
                ('recovery_of_px', models.FloatField(help_text='%', verbose_name='Recovery of PX')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='U800',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('capacity_percent', models.FloatField(verbose_name='Capacity %')),
                ('feed_rate', models.FloatField(help_text='334.5', verbose_name='Reaction Feed Flow(T/hr)')),
                ('t_8001_bottom_px_percent', models.FloatField(help_text='0.2257', verbose_name='T-8001 Bottom, PX%')),
                ('recycle_flow_nm3_hr', models.FloatField(help_text='344833', verbose_name='Recycle Flow [NM3/HR]')),
                ('t_8001_aro_rec', models.FloatField(help_text='335.762', verbose_name='T-8001[T/Hr.](ARO+Rec)')),
                ('feed_to_r_8001_px_percent', models.FloatField(help_text='0.012', verbose_name='Feed to R-8001, Px%')),
                ('feed_to_r_8001_h2_purity', models.FloatField(help_text='51% MOL', verbose_name='Feed to R-8001 :H2  Purity')),
                ('r_8001_inlet_temp', models.FloatField(help_text='374-379', verbose_name='R-8001 Inlet Temp[ ºc]')),
                ('r_8001_delta_t', models.FloatField(help_text='5', verbose_name='R-8001 ΔT')),
                ('h2_hc_ratio', models.FloatField(help_text='2.5~3', verbose_name='H2/HC RATIO')),
                ('r_8001_pressure', models.FloatField(help_text='9 BAR', verbose_name='R-8001 P')),
                ('r_8001_dp', models.FloatField(help_text='0.6', verbose_name='R-8001 ΔP')),
                ('eb_conversion', models.FloatField(help_text='0.645', verbose_name='EB Conversion')),
                ('d_8004a_b_inlet_temp', models.FloatField(help_text='170-200', verbose_name='D-8004A/B : Inlet Temp')),
                ('d_8004a_dp', models.FloatField(help_text='1.5', verbose_name='D-8004A ΔP')),
                ('d_8004b_dp', models.FloatField(help_text='1.5', verbose_name='D-8004B ΔP')),
                ('bri_clay_outlet_max', models.FloatField(help_text='10 MAX', verbose_name='Br.I in clay outlet')),
                ('unit_800_recycle', models.FloatField(help_text='Sm3/hr', verbose_name='Unit 800  Recycle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='U950',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('capacity_percent', models.FloatField(verbose_name='Capacity %')),
                ('feed_rate', models.FloatField(help_text='113', verbose_name='FEED RATE [T/Hr]')),
                ('reactor_inlet_temp', models.FloatField(help_text='260', verbose_name='Reactor Inlet Temp [ ºc]')),
                ('r_9501_pressure', models.FloatField(help_text='28.7', verbose_name='R-9501 Pressure(bar)')),
                ('reactor_delta_t', models.FloatField(help_text='14', verbose_name='Reactor ΔT')),
                ('reactor_dp', models.FloatField(help_text='2', verbose_name='Reactor ΔP')),
                ('recycle_flow_nm3_hr', models.FloatField(help_text='29000', verbose_name='Recycle Flow [NM3/HR]')),
                ('feed_to_r_9501_h2_purity', models.FloatField(help_text='80', verbose_name='Feed To R-9501 H2 Purity')),
                ('off_gas', models.CharField(blank=True, max_length=255, null=True, verbose_name='Off gas to FG / Flare/ VG')),
                ('h2_hc_ratio_min', models.FloatField(help_text='MIN 0.6', verbose_name='H2/HC Ratio')),
                ('product_total_sulphur_ppm', models.FloatField(help_text='300 ppm(ims)', verbose_name='Product Total Sulphur[PPM]')),
                ('light_end_product_t_hr', models.FloatField(help_text='107.5', verbose_name='Light End product[T/Hr]')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='U970',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('capacity_percent', models.FloatField(verbose_name='Capacity %')),
                ('feed_rate', models.FloatField(help_text='150', verbose_name='FEED RATE [T/Hr]')),
                ('light_lte_product_t_hr', models.FloatField(help_text='105', verbose_name='Light LTE Product [T/Hr]')),
                ('heavy_lte_product_t_hr', models.FloatField(help_text='45', verbose_name='Heavy LTE Product [T/Hr]')),
                ('heavy_lte_rvp_psia', models.CharField(help_text='8~10', max_length=50, verbose_name='Heavy LTE RVP [Psia]')),
                ('t_9701_bottom_temp', models.FloatField(help_text='...', verbose_name='T-9701 Bottom Temp.[ ºC]')),
                ('bz_hlte_percent', models.FloatField(help_text='%', verbose_name='BZ (HLTE)')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
