# Generated by Django 5.1.2 on 2024-10-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('px', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='u400',
            name='bz_t_4001_bott',
            field=models.FloatField(blank=True, help_text='0', null=True, verbose_name='BZ at T-4001 Bott'),
        ),
        migrations.AlterField(
            model_name='u400',
            name='c8_aro_top_t_4001',
            field=models.FloatField(blank=True, help_text='0.1', null=True, verbose_name='C8 ARO (Top T-4001) (%)'),
        ),
        migrations.AlterField(
            model_name='u400',
            name='c9_aro_top_t_4002',
            field=models.FloatField(blank=True, help_text='0.05', null=True, verbose_name='C9 ARO (Top T-4002) (%)'),
        ),
        migrations.AlterField(
            model_name='u400',
            name='c9_aro_top_t_4003',
            field=models.FloatField(blank=True, help_text='0.05', null=True, verbose_name='C9 ARO (Top T-4003) (%)'),
        ),
        migrations.AlterField(
            model_name='u400',
            name='capacity_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Capacity %'),
        ),
        migrations.AlterField(
            model_name='u400',
            name='d_4005a_b_inlet_temp',
            field=models.FloatField(blank=True, help_text='170-199', null=True, verbose_name='D-4005A/B : Inlet Temp'),
        ),
        migrations.AlterField(
            model_name='u400',
            name='d_4005a_dp',
            field=models.FloatField(blank=True, help_text='1.5', null=True, verbose_name='D-4005A ΔP'),
        ),
        migrations.AlterField(
            model_name='u400',
            name='d_4005b_dp',
            field=models.FloatField(blank=True, help_text='1.5', null=True, verbose_name='D-4005B ΔP'),
        ),
        migrations.AlterField(
            model_name='u400',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='u400',
            name='edf_feed_rate',
            field=models.FloatField(blank=True, help_text='126.88', null=True, verbose_name='EDF[T/Hr]'),
        ),
        migrations.AlterField(
            model_name='u400',
            name='feed_rate',
            field=models.FloatField(blank=True, help_text='646.858', null=True, verbose_name='FEED RATE [T/Hr]'),
        ),
        migrations.AlterField(
            model_name='u400',
            name='non_aro_on_ox',
            field=models.FloatField(blank=True, help_text='1% IMS', null=True, verbose_name='Non Aro. On OX'),
        ),
        migrations.AlterField(
            model_name='u400',
            name='non_aro_t_4001_bott',
            field=models.FloatField(blank=True, help_text='0.3', null=True, verbose_name='Non Aro at T-4001 Bott'),
        ),
        migrations.AlterField(
            model_name='u400',
            name='non_aro_t_4002_top',
            field=models.FloatField(blank=True, help_text='0.1', null=True, verbose_name='Non Aro at T-4002 top'),
        ),
        migrations.AlterField(
            model_name='u400',
            name='non_aro_t_4003_top',
            field=models.FloatField(blank=True, help_text='0.1', null=True, verbose_name='Non Aro at T-4003 top'),
        ),
        migrations.AlterField(
            model_name='u400',
            name='ox_production_rate',
            field=models.FloatField(blank=True, help_text='12.626', null=True, verbose_name='OX PRODUCTION RATE T/h'),
        ),
        migrations.AlterField(
            model_name='u400',
            name='ox_purity',
            field=models.FloatField(blank=True, help_text='0.985', null=True, verbose_name='OX PURITY(%)'),
        ),
        migrations.AlterField(
            model_name='u400',
            name='t_4001_feed_rate',
            field=models.FloatField(blank=True, help_text='238.26', null=True, verbose_name='T-4001[T/Hr]'),
        ),
        migrations.AlterField(
            model_name='u400',
            name='t_4002_total_feed_rate',
            field=models.FloatField(blank=True, help_text='375.2', null=True, verbose_name='T-4002[T/Hr] Total'),
        ),
        migrations.AlterField(
            model_name='u400',
            name='t_4003_total_feed_rate',
            field=models.FloatField(blank=True, help_text='144.8', null=True, verbose_name='T-4003[T/Hr] Total'),
        ),
        migrations.AlterField(
            model_name='u400',
            name='t_4004_feed_rate',
            field=models.FloatField(blank=True, help_text='46.079', null=True, verbose_name='T-4004[T/Hr]'),
        ),
        migrations.AlterField(
            model_name='u400',
            name='tol_t_4001_bott',
            field=models.FloatField(blank=True, help_text='0.4', null=True, verbose_name='TOL at T-4001 Bott'),
        ),
        migrations.AlterField(
            model_name='u700',
            name='bri_feed_to_t_7001a_b',
            field=models.FloatField(blank=True, help_text='MAX 10', null=True, verbose_name='Br.I in Feed to T-7001A/B'),
        ),
        migrations.AlterField(
            model_name='u700',
            name='capacity_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Capacity %'),
        ),
        migrations.AlterField(
            model_name='u700',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='u700',
            name='feed_t_7001_a_b',
            field=models.FloatField(blank=True, help_text='426.57', null=True, verbose_name='FEED T-7001 A/B T/H'),
        ),
        migrations.AlterField(
            model_name='u700',
            name='make_up_recycle_pdeb_purity',
            field=models.FloatField(blank=True, help_text='>98%wt', null=True, verbose_name='Make up/ Recycle PDEB Purity'),
        ),
        migrations.AlterField(
            model_name='u700',
            name='pdeb_in_px_prod',
            field=models.FloatField(blank=True, help_text='0', null=True, verbose_name='PDEB In:PX Prod.'),
        ),
        migrations.AlterField(
            model_name='u700',
            name='pdeb_in_side_cut',
            field=models.FloatField(blank=True, help_text='0', null=True, verbose_name='PDEB In: Side Cut:'),
        ),
        migrations.AlterField(
            model_name='u700',
            name='px_on_raffinate',
            field=models.FloatField(blank=True, help_text='0.005', null=True, verbose_name='Px on Raffinate:'),
        ),
        migrations.AlterField(
            model_name='u700',
            name='px_purity',
            field=models.FloatField(blank=True, help_text='99.7', null=True, verbose_name='PURITY OF PX'),
        ),
        migrations.AlterField(
            model_name='u700',
            name='px_rate',
            field=models.FloatField(blank=True, help_text='94.205', null=True, verbose_name='Px Rate[T/Hr.]'),
        ),
        migrations.AlterField(
            model_name='u700',
            name='recovery_of_px',
            field=models.FloatField(blank=True, help_text='%', null=True, verbose_name='Recovery of PX'),
        ),
        migrations.AlterField(
            model_name='u700',
            name='t_7001a_dp',
            field=models.FloatField(blank=True, help_text='MAX 4.5', null=True, verbose_name='T-7001A ΔP( MAX) Within 24 Hour'),
        ),
        migrations.AlterField(
            model_name='u700',
            name='t_7001a_temp',
            field=models.FloatField(blank=True, help_text='175', null=True, verbose_name='T-7001A/B Temp.[ ºc]'),
        ),
        migrations.AlterField(
            model_name='u700',
            name='t_7001b_dp',
            field=models.FloatField(blank=True, help_text='MAX 4.5', null=True, verbose_name='T-7001B ΔP(MAX) Within 24 Hour'),
        ),
        migrations.AlterField(
            model_name='u700',
            name='tol_rate',
            field=models.FloatField(blank=True, help_text='1.881', null=True, verbose_name='TOL Rate[T/Hr.]'),
        ),
        migrations.AlterField(
            model_name='u700',
            name='tuning_status',
            field=models.CharField(help_text='New Setpoint', max_length=100, verbose_name='Tuning Status'),
        ),
        migrations.AlterField(
            model_name='u700',
            name='water_desorbent_ppm',
            field=models.FloatField(blank=True, help_text='MAx 140 ppm', null=True, verbose_name='Water: Desorbent [ ppm]'),
        ),
        migrations.AlterField(
            model_name='u700',
            name='water_feed_ppm',
            field=models.FloatField(blank=True, help_text='max 40', null=True, verbose_name='Water: Feed [ ppm]'),
        ),
        migrations.AlterField(
            model_name='u700',
            name='water_injection',
            field=models.FloatField(blank=True, help_text='100', null=True, verbose_name='Water injection (Kg/Hr)'),
        ),
        migrations.AlterField(
            model_name='u700',
            name='water_raff_ppm',
            field=models.FloatField(blank=True, help_text='MAx 100 ppm', null=True, verbose_name='Water: Raff [ ppm]'),
        ),
        migrations.AlterField(
            model_name='u800',
            name='bri_clay_outlet_max',
            field=models.FloatField(blank=True, help_text='10 MAX', null=True, verbose_name='Br.I in clay outlet'),
        ),
        migrations.AlterField(
            model_name='u800',
            name='capacity_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Capacity %'),
        ),
        migrations.AlterField(
            model_name='u800',
            name='d_8004a_b_inlet_temp',
            field=models.FloatField(blank=True, help_text='170-200', null=True, verbose_name='D-8004A/B : Inlet Temp'),
        ),
        migrations.AlterField(
            model_name='u800',
            name='d_8004a_dp',
            field=models.FloatField(blank=True, help_text='1.5', null=True, verbose_name='D-8004A ΔP'),
        ),
        migrations.AlterField(
            model_name='u800',
            name='d_8004b_dp',
            field=models.FloatField(blank=True, help_text='1.5', null=True, verbose_name='D-8004B ΔP'),
        ),
        migrations.AlterField(
            model_name='u800',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='u800',
            name='eb_conversion',
            field=models.FloatField(blank=True, help_text='0.645', null=True, verbose_name='EB Conversion'),
        ),
        migrations.AlterField(
            model_name='u800',
            name='feed_rate',
            field=models.FloatField(blank=True, help_text='334.5', null=True, verbose_name='Reaction Feed Flow(T/hr)'),
        ),
        migrations.AlterField(
            model_name='u800',
            name='feed_to_r_8001_h2_purity',
            field=models.FloatField(blank=True, help_text='51% MOL', null=True, verbose_name='Feed to R-8001 :H2  Purity'),
        ),
        migrations.AlterField(
            model_name='u800',
            name='feed_to_r_8001_px_percent',
            field=models.FloatField(blank=True, help_text='0.012', null=True, verbose_name='Feed to R-8001, Px%'),
        ),
        migrations.AlterField(
            model_name='u800',
            name='h2_hc_ratio',
            field=models.FloatField(blank=True, help_text='2.5~3', null=True, verbose_name='H2/HC RATIO'),
        ),
        migrations.AlterField(
            model_name='u800',
            name='r_8001_delta_t',
            field=models.FloatField(blank=True, help_text='5', null=True, verbose_name='R-8001 ΔT'),
        ),
        migrations.AlterField(
            model_name='u800',
            name='r_8001_dp',
            field=models.FloatField(blank=True, help_text='0.6', null=True, verbose_name='R-8001 ΔP'),
        ),
        migrations.AlterField(
            model_name='u800',
            name='r_8001_inlet_temp',
            field=models.FloatField(blank=True, help_text='374-379', null=True, verbose_name='R-8001 Inlet Temp[ ºc]'),
        ),
        migrations.AlterField(
            model_name='u800',
            name='r_8001_pressure',
            field=models.FloatField(blank=True, help_text='9 BAR', null=True, verbose_name='R-8001 P'),
        ),
        migrations.AlterField(
            model_name='u800',
            name='recycle_flow_nm3_hr',
            field=models.FloatField(blank=True, help_text='344833', null=True, verbose_name='Recycle Flow [NM3/HR]'),
        ),
        migrations.AlterField(
            model_name='u800',
            name='t_8001_aro_rec',
            field=models.FloatField(blank=True, help_text='335.762', null=True, verbose_name='T-8001[T/Hr.](ARO+Rec)'),
        ),
        migrations.AlterField(
            model_name='u800',
            name='t_8001_bottom_px_percent',
            field=models.FloatField(blank=True, help_text='0.2257', null=True, verbose_name='T-8001 Bottom, PX%'),
        ),
        migrations.AlterField(
            model_name='u800',
            name='unit_800_recycle',
            field=models.FloatField(blank=True, help_text='Sm3/hr', null=True, verbose_name='Unit 800  Recycle'),
        ),
        migrations.AlterField(
            model_name='u950',
            name='capacity_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Capacity %'),
        ),
        migrations.AlterField(
            model_name='u950',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='u950',
            name='feed_rate',
            field=models.FloatField(blank=True, help_text='113', null=True, verbose_name='FEED RATE [T/Hr]'),
        ),
        migrations.AlterField(
            model_name='u950',
            name='feed_to_r_9501_h2_purity',
            field=models.FloatField(blank=True, help_text='80', null=True, verbose_name='Feed To R-9501 H2 Purity'),
        ),
        migrations.AlterField(
            model_name='u950',
            name='h2_hc_ratio_min',
            field=models.FloatField(blank=True, help_text='MIN 0.6', null=True, verbose_name='H2/HC Ratio'),
        ),
        migrations.AlterField(
            model_name='u950',
            name='light_end_product_t_hr',
            field=models.FloatField(blank=True, help_text='107.5', null=True, verbose_name='Light End product[T/Hr]'),
        ),
        migrations.AlterField(
            model_name='u950',
            name='off_gas',
            field=models.CharField(blank=True, help_text='str', max_length=50, null=True, verbose_name='Off gas to FG / Flare/ VG'),
        ),
        migrations.AlterField(
            model_name='u950',
            name='product_total_sulphur_ppm',
            field=models.FloatField(blank=True, help_text='300 ppm(ims)', null=True, verbose_name='Product Total Sulphur[PPM]'),
        ),
        migrations.AlterField(
            model_name='u950',
            name='r_9501_pressure',
            field=models.FloatField(blank=True, help_text='28.7', null=True, verbose_name='R-9501 Pressure(bar)'),
        ),
        migrations.AlterField(
            model_name='u950',
            name='reactor_delta_t',
            field=models.FloatField(blank=True, help_text='14', null=True, verbose_name='Reactor ΔT'),
        ),
        migrations.AlterField(
            model_name='u950',
            name='reactor_dp',
            field=models.FloatField(blank=True, help_text='2', null=True, verbose_name='Reactor ΔP'),
        ),
        migrations.AlterField(
            model_name='u950',
            name='reactor_inlet_temp',
            field=models.FloatField(blank=True, help_text='260', null=True, verbose_name='Reactor Inlet Temp [ ºc]'),
        ),
        migrations.AlterField(
            model_name='u950',
            name='recycle_flow_nm3_hr',
            field=models.FloatField(blank=True, help_text='29000', null=True, verbose_name='Recycle Flow [NM3/HR]'),
        ),
        migrations.AlterField(
            model_name='u970',
            name='bz_hlte_percent',
            field=models.FloatField(blank=True, help_text='%', null=True, verbose_name='BZ (HLTE)'),
        ),
        migrations.AlterField(
            model_name='u970',
            name='capacity_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Capacity %'),
        ),
        migrations.AlterField(
            model_name='u970',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='u970',
            name='feed_rate',
            field=models.FloatField(blank=True, help_text='150', null=True, verbose_name='FEED RATE [T/Hr]'),
        ),
        migrations.AlterField(
            model_name='u970',
            name='heavy_lte_product_t_hr',
            field=models.FloatField(blank=True, help_text='45', null=True, verbose_name='Heavy LTE Product [T/Hr]'),
        ),
        migrations.AlterField(
            model_name='u970',
            name='heavy_lte_rvp_psia',
            field=models.FloatField(blank=True, help_text='8~10', null=True, verbose_name='Heavy LTE RVP [Psia]'),
        ),
        migrations.AlterField(
            model_name='u970',
            name='light_lte_product_t_hr',
            field=models.FloatField(blank=True, help_text='105', null=True, verbose_name='Light LTE Product [T/Hr]'),
        ),
        migrations.AlterField(
            model_name='u970',
            name='t_9701_bottom_temp',
            field=models.FloatField(blank=True, help_text='...', null=True, verbose_name='T-9701 Bottom Temp.[ ºC]'),
        ),
    ]
